### ISSUE TITLE
curate base classes

### ISSUE THREAD

**Issue by moodymudskipper** [cynkra/constructive#357]
Some of those can be constructed, some cannot, some are computed, some are not classes, some are done already.

I think when they can be produce by querying the state or when they're he reset of a computation that can be inverted, we have a case for having the default constructor be "next". This way when we encounter a class we can checkout the opts_ function and see how this example might be obtained, but we don't impose to the user something that might be not reproducible due to state or system changes, or not exact due to rounding, or slow to run, or less compact than the "next" version.

``` r
pkg_classes <- function(pkg) {
  extract_from_fun <- function(call) {
    if (!is.call(call)) return(NULL)
    if (identical(call[[1]], quote(structure))) {
      #if (is.character(call$class)) return(call$class)
      return(deparse1(call$class))
    }
    if (identical(call[[1]], quote(`<-`)) &&
        is.call(call[[2]])) {
      if( identical(call[[2]][[1]], quote(attr)) &&
          identical(call[[2]][[2]], "class")) {
        return(deparse1(call[[3]]))
      }
      if(identical(call[[2]][[1]], quote(class))) {
        return(deparse1(call[[3]]))
      }
    }
    lapply(call, extract_from_fun)
  }
  
  funs <- Filter(
    function(obj) typeof(obj) == "closure",
    as.list(asNamespace(pkg))
  )
  s3_nms <- Filter(function(x) isS3method(x, envir = asNamespace(pkg)), names(funs))
  nms <- names(funs)
  funs <- lapply(funs, function(x) unique(Filter(
    Negate(is.null), unlist(extract_from_fun(body(x)))
  )))
  funs <- Filter(Negate(is.null), funs)
  funs <- funs[sort(names(funs))]
  df <- stack(funs)
  df <- df[order(df$values, df$ind),]
  df_agg <- aggregate(ind ~ values, df, function(x) toString(paste0("`", x, "`")))
  lines <- sprintf('* [ ] %s (%s)', df_agg$values, df_agg$ind)
  message("from structure(), class<-(), attr<-(, 'class')")
  writeLines(c(lines, ""))
  
  nms <- gsub("data\\.frame", "dataframe", nms)
  s3_nms <- gsub("data\\.frame", "dataframe", s3_nms)
  
  message("from s3 methods suffix and not above")
  cl1 <- sort(unique(sub(".*?[.]([^.]+)$", "\\1", s3_nms)))
  cl1 <- gsub("dataframe", "data.frame", cl1)
  cl1 <- setdiff(cl1, c("default", df_agg$values))
  lines <- sprintf('* [ ] "%s"', cl1)
  writeLines(c(lines, ""))
  
  
  message("from is* and as* function names and not above")
  cl2 <- grep("^(as|is)[._].*", nms, value = TRUE)
  cl2 <- sort(unique(sub("^(as|is)[._](.*?)([.].*)?$", "\\2", cl2)))
  cl2 <- gsub("dataframe", "data.frame", cl2)
  cl2 <- setdiff(cl2, c("default", df_agg$values, cl1))
  lines <- sprintf('* [ ] "%s"', cl2)
  writeLines(c(lines, ""))
}
````

## Done
* [x] "array"
* [x] "AsIs"
* [x] "character"
* [x] "complex"
* [x] "data.frame"
* [x] "Date"
* [x] "double"
* [x] "environment"
* [x] "expression"
* [x] "factor"
* [x] "formula"
* [x] "function"
* [x] "integer"
* [x] "language"
* [x] "list"
* [x] "logical"
* [x] "matrix"
* [x] "name"
* [x] "noquote"
* [x] NULL
* [x] "numeric"
* [x] "numeric_version"
* [x] "ordered"
* [x] "package_version"
* [x] "pairlist"
* [x] "POSIXct"
* [x] "POSIXlt"
* [x] "POSIXt"
* [x] "primitive"
* [x] "symbol"
* [x] "raw"
* [x] "ts"

## TODO

* [x] "hexmode" (`as.hexmode`) : feasible, with a "character" (default) and a "numeric" constructor, do outmode at the same time
* [x] "octmode" (`as.octmode`) : see hexmode
* [ ] "try-error" (`try`) : Using try(,silent=TRUE)
* [x] "simpleMessage" (`simpleMessage`)
* [x] "simpleError" (`simpleError`)
* [x] "simpleWarning" (`simpleWarning`)
* [x] "simpleCondition" (`simpleCondition`)* [ ] "error" (`errorCondition`)
* [x] "warning" (`warningCondition`)
* [ ] "difftime" (as.difftime)
* [ ] c("srcfilealias", "srcfile") (`as.character.srcref`, `srcfilealias`): I think this one can be done, not tremendously useful though
* [ ] "single" : this one is little weird, it's an attribute, not a class, so it might need special casing for something obscure and S related, so might not be worth it
* [x] "citationFooter" (`citFooter`)
* [x] "citationHeader" (`citHeader`)
* [x] "person" (`$<-.person`, `c.person`)

## Would require inverse computation

Probably not needed, though would be useful for education and to understand easily where a class comes from.

* [ ] "summaryDefault" (`summary.default`) : we might do this one for atomic because it's very easy, and fall back if it doesn't work
* [ ] "rle" (`rle`) : this one is quite easy though, it's `rle(rep(x$values, x$lengths))`
* [ ] "table" (`[.table`, `table`) : note, we could use as.table on an array but it doesn't look any better
* [ ] c("table", oldClass(x)) (`as.table.default`)
* [ ] _"by" : Can't be done exactly, result of a computation + NSE_, could be done approximately using identity and non matching NSE
* [ ] "det" (`determinant.matrix`) : we can with `determinant(matrix(c(exp(x$modulus), 0, 0, x$sign), 2))` 
* [ ] "eigen" (`eigen`) : this is `x$vectors %*% diag(x$values) %*% solve(x$vectors)`, but with possible computing errors
* [ ] "qr" (`qr.default`)
* [ ] "summary.table" (`summary.table`)
* [ ] "summary.warnings" (`summary.warnings`)
* [ ] "lm"

## Would require a stable state

* [ ] "Dlist" (`Sys.getenv`) : It's the output of `Sys.getenv()` without arg, we could use it when it's identical, and fall back when it's not, but then it's not exactly portable, but then again .GlobalEnv isn't either
* [ ] "DLLRegisteredRoutines" (`getDLLRegisteredRoutines.DLLInfo`) : same idea as above
* [ ] "libraryIQR" : output of library() with missing package and help args
* [ ] "packageInfo" (`library`)
* [ ] "proc_time" (`system.time`)
* [ ] "warnings" (`[.warnings`, `c.warnings`, `warnings`)
* [ ] "srcfile" (`srcfile`)
* [ ] "srcref" (`srcref`)
* [ ] c("srcfilecopy", "srcfile") (`srcfilecopy`)
* [ ] "pipe" the object is different when we recreate it with the same call, so cannot be used in constructive
* [ ] "url": same
* [ ] "file" same
* [ ] "DLLInfo"
* [ ] "DLLInfoList"
* [ ] "DLLRegisteredRoutines"
* [ ] "sessionInfo" (`utils::sessionInfo`)

## not accessible because created by private functions
* [ ] "NativeRoutineMap" : the nativeRoutines element of the output of `parseNamespaceFile()`
* [ ] "restart" (`withRestarts`) : created by makeRestart() inside of withRestarts() and unlikely to be found outside of this function
* [ ] "listof", It's built by modelling functions internally from ?listof :  It is simply a list with an assigned class to control the way methods, especially printing, act on it.

## impossible for other reasons ?

* [ ] "condition" : I think it's always created by other functions, as a secondary class
* [ ] "connection", same think, created as a second class by pipe, url etc, see ?connection

```
pkg_classes("base")
```

from s3 methods suffix and not above

* [ ] "envRefClass"
* [ ] "NativeRoutineList"

```
pkg_classes("utils")
```

from structure(), class<-(), attr<-(, 'class')
* [ ] "bibentry" (`as.bibentry.citation`)
* [ ] "Bibtex" (`toBibtex.bibentry`)
* [ ] "browseVignettes" (`browseVignettes`)
* [ ] "changedFiles" (`changedFiles`)
* [ ] "dump.frames" (`dump.frames`)
* [ ] "fileSnapshot" (`fileSnapshot`)
* [ ] "findLineNumResult" (`findLineNum`)
* [ ] "getAnywhere" (`getAnywhere`)
* [ ] "help_files_with_topic" (`help`)
* [ ] "hsearch_db" (`hsearch_db`)
* [ ] "hsearch" (`help.search`)
* [ ] "Latex" (`toLatex.sessionInfo`)
* [ ] "ls_str" (`ls.str`)
* [ ] "object_size" (`object.size`)
* [ ] "packageDescription" (`packageDescription`)
* [ ] "packageIQR" (`data`, `demo`, `vignette`)
* [ ] "packageStatus" (`packageStatus`)
* [ ] "socket" (`make.socket`)
* [ ] "txtProgressBar" (`txtProgressBar`)
* [ ] "vignette" (`vignette`)
* [ ] c("aspell_inspect_context", "data.frame") (`aspell_inspect_context`)
* [ ] c("aspell", "data.frame") (`aspell`)
* [ ] c("relistable", class(x)) (`as.relistable`)
* [ ] c("summary.packageStatus", "packageStatus") (`summary.packageStatus`)
* [ ] cl (`[.bibentry`, `[[.bibentry`)
* [ ] class(x) (`[.person`, `[[.person`, `rep.bibentry`, `rep.roman`, `unique.bibentry`)
* [ ] class(x0) (`combn`)
* [ ] NULL (`[.bibentry`, `[[.bibentry`, `apropos`, `find`, `index.search`, `packageDate`, `str.data.frame`, `str.default`)
* [ ] setdiff(class(x), "relistable") (`unlist.relistable`)

from s3 methods suffix and not above
* [ ] "aspell"
* [ ] "aspell_inspect_context"
* [ ] "bibentry"
* [ ] "Bibtex"
* [ ] "browseVignettes"
* [ ] "changedFiles"
* [ ] "citation"
* [ ] "fileSnapshot"
* [ ] "findLineNumResult"
* [ ] "ftable"
* [ ] "getAnywhere"
* [ ] "hashtab"
* [ ] "help_files_with_topic"
* [ ] "hsearch"
* [ ] "hsearch_db"
* [ ] "Latex"
* [ ] "ls_str"
* [ ] "MethodsFunction"
* [ ] "news_db"
* [ ] "object_size"
* [ ] "packageDescription"
* [ ] "packageIQR"
* [ ] "packageStatus"
* [ ] "person"
* [ ] "relistable"
* [ ] "roman"
* [ ] "sessionInfo"
* [ ] "socket"
* [ ] "txtProgressBar"
* [ ] "vignette"

from is* and as* function names and not above
* [ ] "personList"

```
pkg_classes("stats")
```

from structure(), class<-(), attr<-(, 'class')
* [ ] "acf" (`acf`, `pacf.default`)
* [ ] "aovproj" (`proj.aov`)
* [ ] "ar" (`ar.burg.default`, `ar.burg.mts`, `ar.mle`, `ar.ols`, `ar.yw.default`, `ar.yw.mts`)
* [ ] "Arima" (`arima`)
* [ ] "arima0" (`arima0`)
* [ ] "coef" (`effects.lm`)
* [ ] "decomposed.ts" (`decompose`)
* [ ] "dendrogram" (`[[.dendrogram`, `as.dendrogram.hclust`, `cut.dendrogram`, `merge.dendrogram`)
* [ ] "density" (`density.default`)
* [ ] "dist" (`as.dist.default`)
* [ ] "dummy_coef_list" (`dummy.coef.aovlist`)
* [ ] "dummy_coef" (`dummy.coef.lm`)
* [ ] "factanal" (`factanal.fit.mle`)
* [ ] "family" (`binomial`, `Gamma`, `gaussian`, `inverse.gaussian`, `poisson`, `quasi`, `quasibinomial`, `quasipoisson`)
* [ ] "ftable" (`ftable.default`, `read.ftable`)
* [ ] "hclust" (`as.hclust.dendrogram`, `as.hclust.twins`, `hclust`)
* [ ] "HoltWinters" (`HoltWinters`)
* [ ] "htest" (`ansari.test.default`, `bartlett.test.default`, `binom.test`, `Box.test`, `chisq.test`, `cor.test.default`, `fisher.test`, `fligner.test.default`, `friedman.test.default`, `kruskal.test.default`, `mantelhaen.test`, `mauchly.test.SSD`, `mcnemar.test`, `mood.test.default`, `oneway.test`, `poisson.test`, `PP.test`, `prop.test`, `prop.trend.test`, `quade.test.default`, `shapiro.test`, `t.test.default`, `wilcox.test.default`)
* [ ] "infl" (`influence.measures`)
* [ ] "integrate" (`integrate`)
* [ ] "isoreg" (`isoreg`)
* [ ] "kmeans" (`kmeans`)
* [ ] "link-glm" (`make.link`, `power`)
* [ ] "loadings" (`factanal`, `factanal.fit.mle`, `princomp.default`, `promax`, `varimax`)
* [ ] "loess" (`simpleLoess`)
* [ ] "logLik" (`logLik.Arima`, `logLik.glm`, `logLik.lm`, `logLik.nls`)
* [ ] "medpolish" (`medpolish`)
* [ ] "mtable" (`alias.lm`, `make.tables.aovproj`, `make.tables.aovprojlist`, `model.tables.aov`, `model.tables.aovlist`, `print.tables_aov`, `se.aov`, `se.aovlist`)
* [ ] "nls" (`nls`)
* [ ] "nlsModel" (`nlsModel`)
* [ ] "Pair" (`Pair`)
* [ ] "pairwise.htest" (`pairwise.prop.test`, `pairwise.t.test`, `pairwise.wilcox.test`)
* [ ] "power.htest" (`power.anova.test`, `power.prop.test`, `power.t.test`)
* [ ] "ppr" (`ppr.default`)
* [ ] "prcomp" (`prcomp.default`)
* [ ] "princomp" (`princomp.default`)
* [ ] "selfStart" (`selfStart.default`, `selfStart.formula`)
* [ ] "smooth.spline" (`smooth.spline`)
* [ ] "spec" (`spec.ar`, `spec.pgram`)
* [ ] "SSD" (`SSD.mlm`)
* [ ] "stl" (`stl`)
* [ ] "StructTS" (`StructTS`)
* [ ] "summary.aovlist" (`summary.aovlist`)
* [ ] "summary.ecdf" (`summary.ecdf`)
* [ ] "summary.glm" (`summary.glm`)
* [ ] "summary.lm" (`summary.lm`)
* [ ] "summary.loess" (`summary.loess`)
* [ ] "summary.manova" (`summary.manova`)
* [ ] "summary.nls" (`summary.nls`)
* [ ] "summary.ppr" (`summary.ppr`)
* [ ] "summary.prcomp" (`summary.prcomp`)
* [ ] "summary.princomp" (`summary.princomp`)
* [ ] "summaryDefault" (`print.summary.ecdf`)
* [ ] "tskernel" (`kernel`)
* [ ] "tukeyline" (`line`)
* [ ] attributes(x) <- NULL (`print.mtable`)
* [ ] c("anova", "data.frame") (`add1.default`, `add1.glm`, `add1.lm`, `anova.glm`, `anova.glmlist`, `anova.lm`, `anova.lmlist`, `anova.loess`, `anova.mlm`, `anova.mlmlist`, `anovalist.nls`, `drop1.default`, `drop1.glm`, `drop1.lm`, `summary.aov`)
* [ ] c("aovlist", "listof") (`aov`)
* [ ] c("aovprojlist", "listof") (`proj.aovlist`)
* [ ] c("ecdf", "stepfun", class(rval)) (`ecdf`)
* [ ] c("ks.test", "htest") (`ks.test.default`)
* [ ] c("manova", oldClass(result)) (`manova`)
* [ ] c("manova", oldClass(result[[i]])) (`manova`)
* [ ] c("nlsModel.plinear", "nlsModel") (`nlsModel.plinear`)
* [ ] c("poly", "matrix") (`poly`, `polym`)
* [ ] c("ppr.form", "ppr") (`ppr.formula`)
* [ ] c("profile.nls", "profile") (`profile.nls`)
* [ ] c("profiler.nls", "profiler") (`profiler.nls`)
* [ ] c("sortedXyData", "data.frame") (`sortedXyData.default`)
* [ ] c("stepfun", class(rval)) (`stepfun`)
* [ ] c("summary.aov", "listof") (`summary.aov`)
* [ ] c("tables_aov", "list.of") (`model.tables.aov`, `model.tables.aovlist`)
* [ ] c("TukeyHSD", "multicomp") (`TukeyHSD.aov`)
* [ ] c("tukeysmooth", if (is.ts(x)) "ts") (`smooth`)
* [ ] c("xtabs", "table") (`xtabs`)
* [ ] c(fit$class, c("glm", "lm")) (`glm`)
* [ ] c(if (inherits(fit, "mlm")) "maov", "aov", oldClass(fit)) (`aov`)
* [ ] c(if (maov) "maov", "aov", oldClass(er.fit)) (`aov`)
* [ ] c(if (mlm) "mlm", "lm") (`lm`)
* [ ] c(oldClass(terms), "formula") (`terms.formula`)
* [ ] cl (`na.contiguous.default`, `na.omit.ts`, `tsp<-`)
* [ ] cl[match("mlm", cl):length(cl)][-1L] (`summary.mlm`)
* [ ] if (any(other)) cl[other] (`t.ts`)
* [ ] if (nser > 1L) c("mts", "ts") else "ts" (`filter`)
* [ ] oldClass(object) (`add1.glm`, `add1.lm`)

from s3 methods suffix and not above
* [ ] "acf"
* [ ] "anova"
* [ ] "aov"
* [ ] "aovlist"
* [ ] "aovproj"
* [ ] "ar"
* [ ] "Arima"
* [ ] "arima0"
* [ ] "coxph"
* [ ] "dendrogram"
* [ ] "density"
* [ ] "dist"
* [ ] "dummy_coef"
* [ ] "dummy_coef_list"
* [ ] "ecdf"
* [ ] "exclude"
* [ ] "factanal"
* [ ] "family"
* [ ] "fit"
* [ ] "ftable"
* [ ] "glm"
* [ ] "glmlist"
* [ ] "hclust"
* [ ] "HoltWinters"
* [ ] "htest"
* [ ] "infl"
* [ ] "integrate"
* [ ] "isoreg"
* [ ] "kmeans"
* [ ] "loadings"
* [ ] "loess"
* [ ] "logLik"
* [ ] "manova"
* [ ] "maov"
* [ ] "medpolish"
* [ ] "mlm"
* [ ] "mlmlist"
* [ ] "mtable"
* [ ] "mts"
* [ ] "negbin"
* [ ] "nls"
* [ ] "omit"
* [ ] "packageStatus"
* [ ] "perc"
* [ ] "poly"
* [ ] "ppr"
* [ ] "prcomp"
* [ ] "princomp"
* [ ] "selfStart"
* [ ] "sortedXyData"
* [ ] "spec"
* [ ] "spline"
* [ ] "SSD"
* [ ] "stepfun"
* [ ] "stl"
* [ ] "StructTS"
* [ ] "survreg"
* [ ] "tables_aov"
* [ ] "terms"
* [ ] "tskernel"
* [ ] "TukeyHSD"
* [ ] "tukeyline"
* [ ] "tukeysmooth"
* [ ] "twins"
* [ ] "xtabs"

from is* and as* function names and not above
* [ ] "empty"
* [ ] "leaf"

```
pkg_classes("methods")
```

from s3 methods suffix and not above
* [ ] "MethodsList"

```
pkg_classes("graphics")
```

from structure(), class<-(), attr<-(, 'class')
* [ ] "histogram" (`hist.default`)
